#!/usr/bin/env bash
#
# Non-regression script
#

set -e

TEMPLATES=$(ls data/templates | sed 's/common//g')
PROJECTS=( libacme quux 'Frob Baz' )
OUTDIR=/tmp/yaprogen-tmp
DESTDIR=/tmp/yaprogen-res

rm -rf $OUTDIR $DESTDIR

for project in "${PROJECTS[@]}"; do
    for template in $TEMPLATES; do
        echo "** Generating $project using $template **"
        prefix=$(echo $DESTDIR/$template/$project | sed 's/ /-/g')
        workdir=$(echo $OUTDIR/$template/$project | sed 's/ /-/g')
        yaprogen create -o "$workdir" "$template" "$project"
        (cd "$workdir";
            if [ -f CMakeLists.txt ]; then
                cmake . -DCMAKE_INSTALL_PREFIX="$prefix"
                make install
            elif [ -f autogen.sh ]; then
                ./autogen.sh --prefix="$prefix"
                make install
            elif [ -f "$project.pro" ]; then
                qmake PREFIX="$prefix"
                make install
            fi
        )
    done;
done

# vim: ts=4 sts=4 sw=4 et ai
