#!/usr/bin/env bash
#
# Non-regression script
#

set -e

TEMPLATES=$(ls data/templates | sed 's/common//g')
PROJECTS=( libacme quux 'Frob Baz' )
OUTDIR=/tmp/yaprogen-tmp
DESTDIR=/tmp/yaprogen-res
QMAKE=${QMAKE:-qmake}

rm -rf $OUTDIR $DESTDIR

for project in "${PROJECTS[@]}"; do
    for template in $TEMPLATES; do
        echo "** Generating $project using $template **"
        prefix=$(sed 's/ /-/g' <<< "$DESTDIR/$template/$project")
        workdir=$(sed 's/ /-/g' <<< "$OUTDIR/$template/$project")
        yaprogen create -o "$workdir" "$template" "$project"
        (cd "$workdir";
            if [ -f CMakeLists.txt ]; then
                cmake . -DCMAKE_INSTALL_PREFIX="$prefix"
                make install
            elif [ -f autogen.sh ]; then
                ./autogen.sh --prefix="$prefix"
                make install
            elif [ -f "$project.pro" ]; then
                ${QMAKE} PREFIX="$prefix"
                make install
            elif [ -f meson.build ]; then
                mkdir build
                meson --prefix="$prefix" . build
                ninja -v -C build install
            else
                echo "Skipping..."
            fi
        )
    done
done

# vim: ts=4 sts=4 sw=4 et ai
